import { useState, useEffect } from 'react';
import { useTechnologies } from '../hooks/useTechnologies';
import { SkeletonCard } from '../components/SkeletonCard';
import TechnologyChart from '../components/TechnologyChart';
import ComparisonView from '../components/ComparisonView';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { toast } from 'sonner';

import { useSocket } from '../context/SocketContext';

export const Dashboard = () => {
    const { data, loading, error, refreshData, analyzeTechnology } = useTechnologies();
    const { latestTrend } = useSocket();

    // Effect to handle incoming real-time trends
    useEffect(() => {
        if (latestTrend) {
            toast.message('New Intelligence Received', {
                description: latestTrend.title,
                action: {
                    label: 'Analyze',
                    onClick: () => handleAnalyze(latestTrend.title) // Pre-fill analysis
                }
            });
            // Optionally auto-refresh data or append to list locally
            refreshData();
        }
    }, [latestTrend]);

    const [selectedTech, setSelectedTech] = useState(null);
    const [searchTerm, setSearchTerm] = useState('');
    const [isComparisonOpen, setIsComparisonOpen] = useState(false);

    // Initialize Dark Mode removed (handled in App context/Header)
    // But Chart needs to know color mode. For now we will check document class
    const [isDarkMode, setIsDarkMode] = useState(document.documentElement.classList.contains('dark'));

    useEffect(() => {
        // Observer to update chart color when class changes
        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                if (mutation.attributeName === 'class') {
                    setIsDarkMode(document.documentElement.classList.contains('dark'));
                }
            });
        });
        observer.observe(document.documentElement, { attributes: true });
        return () => observer.disconnect();
    }, []);


    const filteredData = data.filter(tech =>
        tech.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    // Auto-select first item if nothing selected and data exists (only on initial load)
    useEffect(() => {
        if (!selectedTech && filteredData.length > 0 && searchTerm === '') {
            setSelectedTech(filteredData[0]);
        }
    }, [data, loading]); // Dependency on data load

    const currentTech = selectedTech
        ? data.find(t => t._id === selectedTech._id) || selectedTech
        : null;

    const handleTechClick = (tech) => {
        setSelectedTech(tech);
    };

    const handleAnalyze = async (term) => {
        if (!term) return;
        toast.promise(analyzeTechnology(term), {
            loading: `Analyzing ${term}...`,
            success: (data) => {
                setSearchTerm('');
                return `${data.name} analysis complete!`;
            },
            error: 'Failed to analyze technology'
        });
    };

    const handleRefresh = async () => {
        toast.promise(refreshData(), {
            loading: 'Refreshing market data...',
            success: 'Market data updated!',
            error: 'Failed to update data'
        });
    };

    const generatePDF = (tech) => {
        try {
            const doc = new jsPDF();

            // Title
            doc.setFontSize(22);
            doc.text(`Analysis Report: ${tech.name}`, 14, 20);

            // Meta Data
            doc.setFontSize(12);
            doc.setTextColor(100);
            doc.text(`Generated by Flux - ${new Date().toLocaleDateString()}`, 14, 30);

            // Stats Block
            doc.setDrawColor(200);
            doc.setFillColor(245, 245, 245);
            doc.rect(14, 40, 180, 25, 'F'); // Box

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text("HYPE SCORE", 20, 48);
            doc.text("STATUS", 80, 48);
            doc.text("SENTIMENT", 140, 48);

            doc.setFontSize(14);
            doc.setTextColor(0);
            doc.text(String(tech.hypeScore), 20, 58);
            doc.text(tech.status, 80, 58);
            doc.text(tech.sentiment?.label || "Neutral", 140, 58);

            // News Table
            if (tech.news && tech.news.length > 0) {
                doc.setFontSize(14);
                doc.text("Latest Intelligence", 14, 80);

                const tableData = tech.news.map(article => [
                    article.source,
                    article.title, // Title wrap handled by autoTable
                    new Date(article.publishedAt).toLocaleDateString()
                ]);

                doc.autoTable({
                    startY: 85,
                    head: [['Source', 'Headline', 'Date']],
                    body: tableData,
                    theme: 'grid',
                    headStyles: { fillColor: [0, 0, 0] }, // Black header
                    styles: { fontSize: 10, cellPadding: 3 }
                });
            }

            doc.save(`${tech.name}_Flux_Report.pdf`);
            toast.success(`Report for ${tech.name} downloaded!`);
        } catch (e) {
            toast.error('Failed to generate PDF');
        }
    };

    const getStatusColor = (status) => {
        switch (status) {
            case 'Booming': return 'text-green-600 bg-green-50 dark:bg-green-900/20 dark:text-green-400';
            case 'Fading': return 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400';
            case 'Stable': return 'text-blue-500 bg-blue-50 dark:bg-blue-900/20 dark:text-blue-400';
            default: return 'text-gray-500 bg-gray-50 dark:bg-neutral-800 dark:text-neutral-400';
        }
    };

    return (
        <>
            {isComparisonOpen && (
                <ComparisonView
                    technologies={data}
                    onClose={() => setIsComparisonOpen(false)}
                    analyzeTechnology={analyzeTechnology}
                />
            )}

            {/* Control Toolbar */}
            <div className="max-w-7xl mx-auto px-6 py-6 w-full sticky top-16 z-10 pointer-events-none">
                <div className="pointer-events-auto flex flex-col md:flex-row gap-4 justify-between items-center bg-white/80 backdrop-blur-md dark:bg-neutral-900/80 p-2 rounded-2xl md:bg-transparent md:dark:bg-transparent md:p-0">
                    {/* Search */}
                    <div className="relative w-full md:max-w-md">
                        <input
                            type="text"
                            placeholder="Search or Add new tech..."
                            className="w-full pl-10 pr-4 py-3 rounded-full border border-neutral-200 bg-white shadow-sm focus:outline-none focus:ring-2 focus:ring-black/5 dark:bg-neutral-800 dark:border-neutral-700 dark:focus:ring-white/20 transition-all font-medium text-sm"
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter' && searchTerm) {
                                    handleAnalyze(searchTerm);
                                }
                            }}
                        />
                        <svg xmlns="http://www.w3.org/2000/svg" className="absolute left-3 top-3.5 h-4 w-4 text-neutral-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                    </div>

                    {/* Actions */}
                    <div className="flex gap-3 w-full md:w-auto">
                        <button
                            onClick={() => setIsComparisonOpen(true)}
                            className="flex-1 md:flex-none px-6 py-3 rounded-full border border-neutral-200 bg-white text-sm font-bold shadow-sm hover:bg-neutral-50 transition-colors dark:bg-neutral-800 dark:border-neutral-700 dark:hover:bg-neutral-700"
                        >
                            Compare
                        </button>

                        <button
                            onClick={handleRefresh}
                            disabled={loading}
                            className={`flex-1 md:flex-none px-6 py-3 rounded-full text-sm font-bold shadow-sm transition-all ${loading
                                ? 'bg-neutral-100 text-neutral-400 dark:bg-neutral-800 dark:text-neutral-600'
                                : 'bg-black text-white hover:bg-neutral-800 active:scale-95 dark:bg-white dark:text-black dark:hover:bg-neutral-200'
                                }`}
                        >
                            {loading ? 'Analyzing...' : 'Refresh'}
                        </button>
                    </div>
                </div>
            </div>

            <main className="max-w-7xl mx-auto px-6 pb-8 flex-grow w-full">
                <div className="grid grid-cols-1 md:grid-cols-12 gap-8 h-full">

                    {/* List View */}
                    <div className="md:col-span-4 lg:col-span-3 space-y-4">
                        <div className="flex justify-between items-center">
                            <h2 className="text-sm font-semibold text-neutral-500 uppercase tracking-wider dark:text-neutral-400">Monitored Tech</h2>
                            <span className="text-xs text-neutral-400 bg-neutral-100 px-2 py-0.5 rounded-full dark:bg-neutral-800">
                                {loading && filteredData.length === 0 ? '...' : filteredData.length}
                            </span>
                        </div>
                        <div className="space-y-2">
                            {loading && filteredData.length === 0 ? (
                                // Skeleton Loader
                                Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />)
                            ) : (
                                filteredData.map((tech) => (
                                    <div
                                        key={tech._id}
                                        onClick={() => handleTechClick(tech)}
                                        className={`group p-4 rounded-xl cursor-pointer border transition-all duration-200 ${currentTech && currentTech._id === tech._id
                                            ? 'bg-white border-neutral-300 shadow-sm ring-1 ring-black/5 dark:bg-neutral-800 dark:border-neutral-600'
                                            : 'bg-transparent border-transparent hover:bg-white hover:border-neutral-200 dark:hover:bg-neutral-800 dark:hover:border-neutral-700'
                                            }`}
                                    >
                                        <div className="flex items-center justify-between">
                                            <span className="font-medium text-lg">{tech.name}</span>
                                            <span className={`text-xs px-2 py-1 rounded-full font-medium ${getStatusColor(tech.status)}`}>
                                                {tech.status}
                                            </span>
                                        </div>
                                        <div className="mt-1 flex items-center justify-between text-sm text-neutral-500 dark:text-neutral-400">
                                            <span>Score: {tech.hypeScore}</span>
                                            <span className={tech.status === 'Booming' ? 'text-green-500' : 'text-neutral-300 dark:text-neutral-600'}>
                                                {tech.status === 'Booming' ? '↗' : '→'}
                                            </span>
                                        </div>
                                    </div>
                                ))
                            )}

                            {filteredData.length === 0 && !loading && (
                                <div className="p-4 text-center text-neutral-400 text-sm">
                                    {error ? (
                                        <span className="text-red-500">Error: {error}. Is the server running?</span>
                                    ) : (
                                        searchTerm ? 'No matches found.' : 'Checking connection...'
                                    )}
                                </div>
                            )}
                        </div>
                    </div >

                    {/* Detail View */}
                    < div className="md:col-span-8 lg:col-span-9" >
                        {
                            currentTech ? (
                                <div className="bg-white rounded-3xl border border-neutral-200 p-8 shadow-sm h-full flex flex-col dark:bg-neutral-800 dark:border-neutral-700" >
                                    <div className="flex items-start justify-between mb-8">
                                        <div>
                                            <span className="text-neutral-400 text-sm font-medium uppercase tracking-wider">Analysis Report</span>
                                            <h2 className="text-4xl font-bold mt-1 mb-2">{currentTech.name}</h2>
                                            <p className="text-neutral-500 max-w-lg dark:text-neutral-400">
                                                Tracking trends and market sentiment.
                                            </p>
                                        </div>
                                        <div className="text-right">
                                            <div className="text-5xl font-light tracking-tighter">
                                                {currentTech.hypeScore}
                                            </div>
                                            <div className={`mt-2 text-sm font-medium px-3 py-1 inline-block rounded-full ${getStatusColor(currentTech.status)}`}>
                                                {currentTech.status.toUpperCase()}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex-grow bg-neutral-50 rounded-2xl p-6 border border-neutral-100 min-h-[400px] dark:bg-neutral-900 dark:border-neutral-700">
                                        <TechnologyChart data={currentTech} color={isDarkMode ? '#fff' : '#000'} />
                                    </div>

                                    <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
                                        <div className="p-4 bg-neutral-50 rounded-xl dark:bg-neutral-900 border border-transparent dark:border-neutral-700">
                                            <div className="text-xs text-neutral-400 uppercase">Data Points</div>
                                            <div className="text-xl font-semibold mt-1">{currentTech.history.length}</div>
                                        </div>
                                        <div className="p-4 bg-neutral-50 rounded-xl dark:bg-neutral-900 border border-transparent dark:border-neutral-700">
                                            <div className="text-xs text-neutral-400 uppercase">Last Update</div>
                                            <div className="text-xl font-semibold mt-1">
                                                {new Date(currentTech.lastUpdated).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                            </div>
                                        </div>
                                        <div className="p-4 bg-neutral-50 rounded-xl dark:bg-neutral-900 border border-transparent dark:border-neutral-700">
                                            <div className="text-xs text-neutral-400 uppercase">Market Sentiment</div>
                                            <div className={`text-xl font-semibold mt-1 ${currentTech.sentiment?.label === 'Positive' ? 'text-green-500' :
                                                currentTech.sentiment?.label === 'Negative' ? 'text-red-500' : 'text-neutral-500'
                                                }`}>
                                                {currentTech.sentiment?.label || 'Neutral'}
                                            </div>
                                        </div>
                                    </div>

                                    {/* Keyword Cloud */}
                                    {currentTech.keywords && currentTech.keywords.length > 0 && (
                                        <div className="mt-8 mb-2">
                                            <h3 className="text-sm font-semibold text-neutral-400 uppercase tracking-widest mb-3">Trending Keywords</h3>
                                            <div className="flex flex-wrap gap-2">
                                                {currentTech.keywords.slice(0, 15).map((kw, idx) => (
                                                    <span
                                                        key={idx}
                                                        className="px-3 py-1 rounded-full bg-neutral-200 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 text-sm font-medium hover:bg-black hover:text-white dark:hover:bg-white dark:hover:text-black transition-colors cursor-default"
                                                        style={{ fontSize: Math.max(0.8, Math.min(1.5, 0.8 + (kw.value / 10))) + 'rem' }}
                                                    >
                                                        {kw.text}
                                                    </span>
                                                ))}
                                            </div>
                                        </div>
                                    )
                                    }

                                    {/* Latest News Feed */}
                                    {
                                        currentTech.news && currentTech.news.length > 0 && (
                                            <div className="mt-8">
                                                <div className="flex items-center justify-between mb-4">
                                                    <h3 className="text-lg font-bold">Latest News</h3>
                                                    <button
                                                        onClick={() => generatePDF(currentTech)}
                                                        className="text-xs font-bold uppercase tracking-wider text-neutral-500 hover:text-black dark:text-neutral-400 dark:hover:text-white transition-colors flex items-center gap-1"
                                                    >
                                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                        </svg>
                                                        Export Report
                                                    </button>
                                                </div>
                                                <div className="space-y-3">
                                                    {currentTech.news.map((article, idx) => (
                                                        <a key={idx} href={article.url} target="_blank" rel="noopener noreferrer" className="block p-4 bg-neutral-50 rounded-xl border border-transparent hover:border-neutral-200 transition-all dark:bg-neutral-900 dark:hover:border-neutral-700 group">
                                                            <h4 className="font-medium text-base group-hover:text-blue-600 transition-colors dark:text-neutral-200 dark:group-hover:text-blue-400 line-clamp-1">{article.title}</h4>
                                                            <div className="flex items-center gap-2 mt-2 text-xs text-neutral-400">
                                                                <span className="font-semibold text-neutral-500 dark:text-neutral-500">{article.source}</span>
                                                                <span>•</span>
                                                                <span>{new Date(article.publishedAt).toLocaleDateString()}</span>
                                                            </div>
                                                        </a>
                                                    ))}
                                                </div>
                                            </div>
                                        )
                                    }
                                </div >
                            ) : (
                                <div className="h-full flex items-center justify-center text-neutral-400">
                                    Select a technology to view analysis
                                </div>
                            )
                        }
                    </div >
                </div >
            </main >
        </>
    );
};
